baseURL = "https://martinlebeda.github.io"
languageCode = "cs-cz"
title = "ML techno notes"
theme = "hyde"

[params]
  description = "Nejen technické postřehy"
  author = "Martin Lebeda"

[[menu.main]]
    name = "Archiv blogu"
    title = "blog section"
    weight = -110
    identifier = "blog"
    url = "/posts/"

[[menu.main]]
    name = "Projekty"
    title = "project section"
    weight = -110
    identifier = "projects"
    url = "/projects/"
